{% set name = "flake8-pep3101" %}
{% set version = "1.1" %}
{% set sha256 = "b57b42133b14dc4ac09169520cb8ebf4802db30babab98e1ebaf9f3a9da2c832" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - flake8 >=3.0

test:
  commands:
    - "flake8 --version | grep flake8_pep3101:"

about:
  home: https://github.com/gforcada/flake8-pep3101
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE
  summary: 'Check for uses of old % formatting rather than .format() method'
  dev_url: https://github.com/gforcada/flake8-pep3101

extra:
  recipe-maintainers:
    - dopplershift
