{% set name = "flake8-pep3101" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1b84b61685f1e631f2f710e5d5ed3ca68b5fc45fb9402fa8ae1b8a9a058a3387

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - flake8

test:
  requires:
    - python {{ python_min }}
  commands:
    - 'flake8 --version | grep flake8-pep3101:'

about:
  home: https://github.com/gforcada/flake8-pep3101
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE
  summary: Check for uses of old % formatting rather than .format() method
  dev_url: https://github.com/gforcada/flake8-pep3101

extra:
  recipe-maintainers:
    - dopplershift
