travis:
  secure:
    BINSTAR_TOKEN: vEVzTafpMNTnZ87QZp4jnrah5RRdKIIGpT3Zl2JYvmeA8E8rtXbX4mTdU1WchVt4KC4dztavBf6xDH3L5tQac2mhdjRXm5pxF2kqFtOk+tsNVxaxPvjJFfmyO5HQgdgPV4gAwtZRgnsd6NyOYxqR8W0lGsNdP24ATjImr3FZfeVct0hIq9kP29coH32cg90jzM9DKOpTpJRRPd6ooa16b6PuKCfFIwAOS6r9xIEBOrZ7Q15k4HCESEV9F2KEBPKB+BFN2d3BTIKPW9B1OyEb/OfAcYBAJZBCWTnA/F5stXXsJ/n4Aj7H3hG6DUQJlyul3YZULMxex5pqoMJec73zbU+ebKOrPS9MMtUn5X/FcQaP8eomuA4nIpBgXE2IY2SHUasU7PqFSeOb7Gefk6jtS5SCldVtL7Obbysda4XTe3A4FgmmYbxuD3sTcwI7NhLVfv4ds99RmbwRgv7tfpJgNR5m2005xp3t6i+udvojmDAHhIH0yK1yctTt0SEp0MlRtKZk6TesiC01Ved6OYJnNCCnkWvoRnu6SdHGYsd9GEvvAZ64PUUXkk3iz7IAj7s4IWd+uu2rVtgrxq4MoUImd/ZjYYvBR7ezYjvzdobFSQb/z0QDFgkBEgUT1k/E0/LAdCxFF1AMfNtRqHlxfJhGHtsWaUOs6wSb/IiqQiP8WaE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
