travis:
  secure:
    BINSTAR_TOKEN: B5T6N77WA+BTImgIXhSvk++aevcvCtfaFRheB1ZIdEpFcZ+OSMVoShq3lvDV/Yn3XxKuxEUGqZuQJ973wgfkDl4lL8vva+S3s94IafOdJyTtp101qnaVa6wVQa/HTriCdJa4CCzucN//f3SlXBozO/HDctzjcyxeZgZg7M8274rCnwKNkgyELb6kYFuDOLUpUL6XF7jCNQQzKFD1QoEJpmBeSv25QwyW4XXvaoBY22PgIBMClwony7WgZ0ZZupdV5rjkfLX34BBekn0jpmMKsv9mweFyvb88dAtHQLD4n8hZUbIUtHzbthHOnVwsUBJI74wMAqSlWHDHonj110fcz2OnwU3paMo4PWDiBXmG9rGs7f72n16ISiNG+dNCq10o1Osd80DYdXoQJsC4F3I0BMo7JRIMZTvnXhjl4a9zYjAmGyaK2yOwqxQtvou8lm1JxKtQl235OePdqz0CwBwe01vOUVrvZNVprfJ/WQWiSwM0G4RBTc7p+HamErHr7PXROVLijZeNdYqUPSe9bQH0hH+hMTGmZ3g9u+J/Erlk4ZUto8D2a9m+9seYGgk9CLWRRbdLaPW2aj3BDIOwpscmKax+2xV3XiINic4CVTHHSTHrWmVksTRLwF4L5I5H3ffcdoPAPdQoDtqP0wAk78RAPzQASqRTk3/NHvJG2n4xCxk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
